---
title: "p8105_hw2_mjn2142"
author: "Matthew Neky"
date: "10/5/2021"
output: github_document
---

```{r setup}
library(tidyverse)
```


### Problem 1



```{r, message = FALSE}
trash_wheel_data = readxl::read_excel("./trash_wheel.xlsx", sheet = "Mr. Trash Wheel") %>%
  janitor::clean_names() %>%
  select(dumpster:homes_powered, -month, -year, -date) %>%
  na.omit() %>% 
  mutate(
    sports_balls = round(sports_balls, digits = 0)
  )
```


### Problem 2

## Cleaning pols-month data

```{r}
pols_month_data = read_csv("./fivethirtyeight_datasets/pols-month.csv") %>% 
  separate(
    col = mon,
    into = c('year', 'month', 'day'),
    sep = '-',
    remove = TRUE,
    convert = TRUE,
    extra = 'warn',
    fill = 'warn'
  ) %>% 
  mutate(
    month = month.abb[month],
    president = recode(prez_gop, '1' = "gop", '0' = "dem")
    ) %>% 
  select(-day, -prez_gop, -prez_dem)
```

## Clean snp data

```{r}
snp_data = read_csv("./fivethirtyeight_datasets/snp.csv") %>% 
  separate(
    col = date,
    into = c('month', 'day', 'year'),
    sep = '/',
    remove = TRUE,
    convert = TRUE,
    extra = 'warn',
    fill = 'warn'
  ) %>% 
  relocate(year, month)
```

## Clean unemployment data

```{r}
unemployment_data = read_csv("./fivethirtyeight_datasets/unemployment.csv") %>% 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment_level"
  ) %>% 
  rename(year = Year)
```

## Join datasets

```{r}
pols_snp_joined = 
  left_join(pols_month_data, snp_data, by = "year", "month")
```



